runtime: go
api_version: go1

handlers:  
- url: /api/auth/?.*$
  script: _go_app
  login: required
  secure: always

- url: /api/admin/?.*$
  script: _go_app
  login: admin
  secure: always
  
- url: /(.*)/static/(.*)
  static_files: frontend/dist/\1/\2
  upload: frontend/dist/.*(js|css|ico|js\.map)$
  secure: always  

- url: /mcq/?.*$
  script: _go_app
  secure: always
  login: required

- url: /.*
  static_files: frontend/dist/unauth/index.html
  upload: frontend/dist/unauth/index.html
  secure: always  

skip_files:
- ^\.git$
- ^\.vscode$
- \.gitignore
- ^app\.yaml
- ^LICENSE
- ^README\..*
- frontend/src/